### ISSUE TITLE
Getting cuda Error when doing sample inference:  

### ISSUE THREAD

**Issue by Zeeshan75** [megapose6d/megapose6d#49]
Hi,

I have followed the installation process and it was successful, But facing the below issue when I am doing the inference code:
```bash
used code: python -m megapose.scripts.run_inference_on_example barbecue-sauce --run-inference 
```
output:

MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
INFO:__main__:Loading model megapose-1.0-RGB-multi-hypothesis.
0:00:05.459684 - Loading model megapose-1.0-RGB-multi-hypothesis.
Known pipe types:Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)

  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
No protocol specified
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
INFO:__main__:Running inference.
0:00:07.624908 - Running inference.
Traceback (most recent call last):
  File "/home/zeeshans/.conda/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zeeshans/.conda/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 225, in <module>
    run_inference(example_dir, args.model)
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 143, in run_inference
    output, _ = pose_estimator.run_inference_pipeline(
  File "/home/zeeshans/.conda/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/inference/pose_estimator.py", line 576, in run_inference_pipeline
    data_TCO_coarse, coarse_extra_data = self.forward_coarse_model(
  File "/home/zeeshans/.conda/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/inference/pose_estimator.py", line 413, in forward_coarse_model
    out_ = coarse_model.forward_coarse(
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/models/pose_rigid.py", line 680, in forward_coarse
    images_crop, K_crop, boxes_rend, boxes_crop = self.crop_inputs(
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/models/pose_rigid.py", line 218, in crop_inputs
    uv = project_points_robust(points, K, TCO)
  File "/home/zeeshans/megapose_check/megapose6d/src/megapose/lib3d/camera_geometry.py", line 49, in project_points_robust
    suv = (P.unsqueeze(1) @ points_3d.unsqueeze(-1)).squeeze(-1)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)` 

may I know what would be this issue?

**Comment by Zeeshan75** [comment]
Uninstalling and installing torch and torchvision worked for me,

conda env create -f conda/environment_full.yaml
conda activate megapose
pip install -e .
pip uninstall torch torchvision -y
pip install torch torchvision
